# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_cat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrpc_cat.proto\x12\x07rpc_cat\"\x0e\n\x0c\x45mptyMessage\" \n\rStringMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nIntMessage\x12\x0f\n\x07message\x18\x01 \x01(\x05\"\x1f\n\x0cTupleMessage\x12\x0f\n\x07message\x18\x01 \x03(\t\"q\n\x0b\x46oodMessage\x12\x32\n\x07message\x18\x01 \x03(\x0b\x32!.rpc_cat.FoodMessage.MessageEntry\x1a.\n\x0cMessageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x9c\x01\n\x07MulType\x12\x10\n\x03str\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\'\n\x03tup\x18\x02 \x01(\x0b\x32\x15.rpc_cat.TupleMessageH\x01\x88\x01\x01\x12\'\n\x04\x66ood\x18\x03 \x01(\x0b\x32\x14.rpc_cat.FoodMessageH\x02\x88\x01\x01\x12\x0e\n\x01i\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\x06\n\x04_strB\x06\n\x04_tupB\x07\n\x05_foodB\x04\n\x02_i\"\x1d\n\nAllMessage\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x32\xcf\x03\n\x06RpcCat\x12;\n\x08get_name\x12\x15.rpc_cat.EmptyMessage\x1a\x16.rpc_cat.StringMessage\"\x00\x12\x37\n\x07get_age\x12\x15.rpc_cat.EmptyMessage\x1a\x13.rpc_cat.IntMessage\"\x00\x12:\n\x08get_love\x12\x15.rpc_cat.EmptyMessage\x1a\x15.rpc_cat.TupleMessage\"\x00\x12>\n\rget_food_once\x12\x15.rpc_cat.EmptyMessage\x1a\x14.rpc_cat.FoodMessage\"\x00\x12\x44\n\x10get_attr_by_name\x12\x16.rpc_cat.StringMessage\x1a\x16.rpc_cat.StringMessage\"\x00\x12T\n\x1cget_attr_by_name_with_stream\x12\x16.rpc_cat.StringMessage\x1a\x16.rpc_cat.StringMessage\"\x00(\x01\x30\x01\x12\x37\n\x07get_all\x12\x15.rpc_cat.EmptyMessage\x1a\x13.rpc_cat.AllMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_cat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOODMESSAGE_MESSAGEENTRY._options = None
  _FOODMESSAGE_MESSAGEENTRY._serialized_options = b'8\001'
  _EMPTYMESSAGE._serialized_start=26
  _EMPTYMESSAGE._serialized_end=40
  _STRINGMESSAGE._serialized_start=42
  _STRINGMESSAGE._serialized_end=74
  _INTMESSAGE._serialized_start=76
  _INTMESSAGE._serialized_end=105
  _TUPLEMESSAGE._serialized_start=107
  _TUPLEMESSAGE._serialized_end=138
  _FOODMESSAGE._serialized_start=140
  _FOODMESSAGE._serialized_end=253
  _FOODMESSAGE_MESSAGEENTRY._serialized_start=207
  _FOODMESSAGE_MESSAGEENTRY._serialized_end=253
  _MULTYPE._serialized_start=256
  _MULTYPE._serialized_end=412
  _ALLMESSAGE._serialized_start=414
  _ALLMESSAGE._serialized_end=443
  _RPCCAT._serialized_start=446
  _RPCCAT._serialized_end=909
# @@protoc_insertion_point(module_scope)
