# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# import os
# import sys
# _root_path = os.path.abspath('..')
# sys.path.insert(0, _root_path)

# -- Project information -----------------------------------------------------

project = 'Document'
copyright = '2022, yan que'
author = 'yan que'

# The full version, including alpha/beta/rc tags
release = '0.0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',	# 实际使用暂时知道一个作用是, 防止html格式混乱问题, 比如点进去一个文档, 其他文档消失(但是又试了没有这个问题了, 所以, 当我没说)
    # 'sphinx.ext.autosectionlabel', 	# 允许直接ref使用标题引用(否则需要给标题定义别名),
                                    # 支持跨文档标题引用(注意标题在多个文档中保持唯一),

    # 'ablog',
    # 'sphinx.ext.intersphinx',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

toctree_includes = ["**"]  # 递归解析所有目录中的toctree
html_theme_options = {
    "nav_depth": 4   # 左侧目录最大深度为4
}

# from sunpy_sphinx_theme.conf import *
# html_theme = 'sunpy'

# error
# from trojanzoo_sphinx_theme import *
# html_theme = 'trojanzoo'

# html_style = "alabaster.css"
# html_theme = "alabaster"
# html_sidebars = {
#     "**": [
#         "about.html",
#         "ablog/postcard.html",
#         "ablog/recentposts.html",
#         "ablog/tagcloud.html",
#         "ablog/categories.html",
#         "ablog/archives.html",
#         "ablog/authors.html",
#         "ablog/languages.html",
#         "ablog/locations.html",
#         "searchbox.html",
#     ]
# }

html_theme = 'furo'
# html_theme = 'yanque_sphinx_theme'
# html_theme_path = ['../submodule/themes']
html_context = {
    # 传入html模版(jinja2)上下文变量使用
    # 'style': 'css/theme.css',
}
html_theme_options = {
#   'pytorch_project': {project},
#   'collapse_navigation': False,
#   'theme_collapse_navigation': True,
#   'theme_includehidden': True,
#   'show_source': False,
}

# html_theme = 'sphinx_rtd_theme'
# html_theme = 'pytorch_sphinx_theme'

# html_theme = 'nervproject'
# html_theme = 'alabaster'
# html_theme = 'nature'
# html_theme = 'scrolls'
# html_theme = 'agogo'
# html_theme = 'haiku'		# 可以
# html_theme = 'pyramid'	# 这个看起来就是python官网的那种
# html_theme = 'bizstyle'
# html_theme_options = {
#     "rightsidebar": "true",
#     # "relbarbgcolor": "black"
# }

# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_theme_options
# https://www.sphinx-doc.org/en/master/usage/theming.html

html_title = f'启 {release}'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
